### ISSUE TITLE
Badly written docs

### ISSUE THREAD

**Issue by mitmelon** [dwgebler/doclite#13]
You have a good library but the read me docs is very bad.

The documentation is badly written... Its not easy for a beginner to understand at all...

You did not differentiate between a document and collection... You are using document as same as collection thereby confusing the reader or user

2) You did not specify or show how data can be added to collections. You just kept pointing out methods that no one even understands where they are from...

Please Take a good look at this documentation for couchbase https://php-on-couch.readthedocs.io/. You will see how the designer highlighted each methods and showed how to insert data properly with expected output.

Your readme does not show how to process the output which is very poor...

It will be good if you can make a change to this. Thanks.

**Comment by dwgebler** [comment]
@mitmelon thank you for your comments. To address a couple of specific points you've raised:

> You did not differentiate between a document and collection... You are using document as same as collection thereby confusing the reader or user

Collections and documents are described and differentiated in a few places in the documents, complete with code examples.

1. The usage overview section under Getting Started https://github.com/dwgebler/doclite#getting-started
2. About Collections https://github.com/dwgebler/doclite#about-collections
3. About Documents https://github.com/dwgebler/doclite#about-documents

> You did not specify or show how data can be added to collections.

Please see both the usage overview under Getting Started and the section Getting and Setting Document Data https://github.com/dwgebler/doclite#getting-and-setting-document-data and Save a Document https://github.com/dwgebler/doclite#save-a-document

> Your readme does not show how to process the output which is very poor

Could you be more specific with what you feel is missing here? DocLite exposes an API via the `Collection` and `Document` types to manipulate and retrieve data. How your application uses these objects and processes the data is up to you.

I welcome any improvements to DocLite and its documentation. Please raise a pull request with your suggested changes and I'll be happy to review it.
