### ISSUE TITLE
unfinit class not found issue

### ISSUE THREAD

**Issue by REDAL** [dwgebler/doclite#18]
@dwgebler  @Awilum  @iGusev 

Hi,

I am trying to give doclite a try, but unfortunately I cant get it setup

it keeps asking for uncaught class, when I reference it, it just shows another one, and so

Uncaught Error: Class 'Gebler\Doclite\Connection\DatabaseConnection' not found in

can you give me pls, a functional example, from referencing to save and get ?

kindest regards

**Comment by dwgebler** [comment]
@REDAL have you installed DocLite via Composer and included the `vendor/autoload.php`?

**Comment by REDAL** [comment]
hi again David,

actually no, I just downloaded it, I dont use composer,

I use wamp with netbeans, I download the source files, and reference them directly with include

**Comment by dwgebler** [comment]
@REDAL it's a namespaced package and is designed to be used via an autoloader. If you're not using Composer, you'll need to write your own autoloader to include the right source files for each referenced class and register it via https://www.php.net/manual/en/function.spl-autoload-register.php

I strongly recommend installing via Composer.

Closing this issue as user error.

**Comment by REDAL** [comment]
I did download it with composer, also cant find autoload

can you please give me any simple PHP project with needed referencing

**Comment by dwgebler** [comment]
@REDAL the instructions are all in the documentation. All you need to do is install via Composer

`composer require dwgebler/doclite`

Then include the generated vendor `autoload.php` file in your project and reference the `FileDatabase` or `MemoryDatabase` class as normal.

```
<?php

use Gebler\Doclite\FileDatabase;

require_once 'vendor/autoload.php';

$db = new FileDatabase('test.db');
$collection = $db->collection('test');
$document = $collection->get();
```

**Comment by REDAL** [comment]
Hi again @dwgebler , thank you for your reply

I did exactly the same, I get this error message


Warning: include(src/Gebler\Doclite\FileDatabase.php): failed to open stream: No such file or directory in E:\wamp3.2.4\www\doclite\index.php on line 6

Warning: include(): Failed opening 'src/Gebler\Doclite\FileDatabase.php' for inclusion (include_path='.;C:\php\pear') in E:\wamp3.2.4\www\doclite\index.php on line 6

Fatal error: Uncaught Error: Class 'Gebler\Doclite\FileDatabase' not found in E:\wamp3.2.4\www\doclite\index.php:11 Stack trace: #0 {main} thrown in E:\wamp3.2.4\www\doclite\index.php on line 11

---------------------------------------------------------------------------------------------

can you tell me pls, what are the needed files to require , and the classes to USE !

cause , I don't know how to make it work , unfortunately

**Comment by REDAL** [comment]
Parse error: syntax error, unexpected '|', expecting ';' or '{' in E:\wamp3.2.4\www\doclite\vendor\symfony\serializer\Encoder\XmlEncoder.php on line 247

**Comment by REDAL** [comment]
@dwgebler  actually it worked,
I found the error is related to php7, doclite, did work under PHP 8 but not 7...

thanks a lot for your time and help David

**Comment by dwgebler** [comment]
@REDAL DocLite works with PHP 7.4 or upwards and will use older versions of Symfony dependencies compatible with 7.4 (Serializer version 5.4) if that is the version of PHP you have. Sounds like you may have installed DocLite using PHP 8 but tried to run your script with 7.4 or 7.2.

**Comment by REDAL** [comment]
for sure !
my bad sorry !

only David, when I try to echo the result of the document found, it shows me a long list of array, can u tell me how to echo only the results 
also, it didn't create an auto generated id for the new document :

Gebler\Doclite\Document Object
(
    [data:Gebler\Doclite\Document:private] => Array
        (
            [__id] => 1
        )

    [id:Gebler\Doclite\Document:private] => 1
    [collection:Gebler\Doclite\Document:private] => Gebler\Doclite\Collection Object
        (
            [db:Gebler\Doclite\Collection:private] => Gebler\Doclite\FileDatabase Object
                (
                    [conn:protected] => Gebler\Doclite\Connection\DatabaseConnection Object
                        (
                            [dsn:protected] => sqlite:E:\wamp3.2.4\www\doclite\users.db
                            [readOnly:protected] => 
                            [conn:protected] => PDO Object
                                (
                                )

                            [queryCache:protected] => Array
                                (
                                    [41169858bd7553571be6ea99e3c316e59bbbc30e5ddbc232877a5b554f7365fb] => PDOStatement Object
                                        (
                                            [queryString] => SELECT name FROM sqlite_master WHERE type='table' AND name=?;
                                        )

                                    [2a9e377cd5f6c403900ea7317ead7941dd071221374975618e01cd9ff3ddc47a] => PDOStatement Object
                                        (
                                            [queryString] => SELECT COUNT(*) FROM sqlite_master WHERE type='index' and name=?
                                        )

                                    [da944c1c020b9d5db7175722ee9e6ba629d16970fe0c3739a8bf1038de250d25] => PDOStatement Object
                                        (
                                            [queryString] => SELECT json FROM users WHERE json_extract(json,'$.__id') = ?
                                        )

                                    [ecb162c42da3cc0f58d4687c034146288179cc70ab1d4d7a7f72dd659ca3041f] => PDOStatement Object
                                        (
                                            [queryString] => INSERT INTO "users" (json) VALUES (json(?))
                                        )

                                    [a2af98f17d08244ae7312e0f2530bbaa507bd494c267fb6641b0460ae4e73e8f] => PDOStatement Object
                                        (
                                            [queryString] => SELECT json FROM "users" WHERE json_array(json_extract(json, ?)) = json_array(?)
                                        )

                                )

                            [timeout:Gebler\Doclite\Connection\DatabaseConnection:private] => 1
                            [ftsEnabled:Gebler\Doclite\Connection\DatabaseConnection:private] => 
                        )

                    [fileSystem:protected] => Gebler\Doclite\FileSystem\FileSystem Object
                        (
                        )

                    [cacheAutoPrune:protected] => 
                    [inTransaction:protected] => 
                    [transactionTable:protected] => 
                    [readOnly:protected] => 
                    [ftsEnabled:protected] => 
                )

            [name:Gebler\Doclite\Collection:private] => users
            [cachingEnabled:Gebler\Doclite\Collection:private] => 
            [cacheLifetime:Gebler\Doclite\Collection:private] => 60
            [serializer:Gebler\Doclite\Collection:private] => Symfony\Component\Serializer\Serializer Object
                (
                    [encoder:protected] => Symfony\Component\Serializer\Encoder\ChainEncoder Object
                        (
                            [encoders:Symfony\Component\Serializer\Encoder\ChainEncoder:private] => Array
                                (
                                    [0] => Symfony\Component\Serializer\Encoder\JsonEncoder Object
                                        (
                                            [encodingImpl:protected] => Symfony\Component\Serializer\Encoder\JsonEncode Object
                                                (
                                                    [defaultContext:Symfony\Component\Serializer\Encoder\JsonEncode:private] => Array
                                                        (
                                                            [json_encode_options] => 0
                                                        )

                                                )

                                            [decodingImpl:protected] => Symfony\Component\Serializer\Encoder\JsonDecode Object
                                                (
                                                    [serializer:protected] => 
                                                    [defaultContext:Symfony\Component\Serializer\Encoder\JsonDecode:private] => Array
                                                        (
                                                            [json_decode_associative] => 1
                                                            [json_decode_options] => 0
                                                            [json_decode_recursion_depth] => 512
                                                        )

                                                )

                                        )

                                    [1] => Symfony\Component\Serializer\Encoder\XmlEncoder Object
                                        (
                                            [defaultContext:Symfony\Component\Serializer\Encoder\XmlEncoder:private] => Array
                                                (
                                                    [as_collection] => 
                                                    [decoder_ignored_node_types] => Array
                                                        (
                                                            [0] => 7
                                                            [1] => 8
                                                        )

                                                    [encoder_ignored_node_types] => Array
                                                        (
                                                        )

                                                    [load_options] => 2304
                                                    [remove_empty_tags] => 
                                                    [xml_root_node_name] => response
                                                    [xml_type_cast_attributes] => 1
                                                )

                                            [serializer:protected] => Symfony\Component\Serializer\Serializer Object
 *RECURSION*
                                        )

                                    [2] => Symfony\Component\Serializer\Encoder\YamlEncoder Object
                                        (
                                            [dumper:Symfony\Component\Serializer\Encoder\YamlEncoder:private] => Symfony\Component\Yaml\Dumper Object
                                                (
                                                    [indentation:Symfony\Component\Yaml\Dumper:private] => 4
                                                )

                                            [parser:Symfony\Component\Serializer\Encoder\YamlEncoder:private] => Symfony\Component\Yaml\Parser Object
                                                (
                                                    [filename:Symfony\Component\Yaml\Parser:private] => 
                                                    [offset:Symfony\Component\Yaml\Parser:private] => 0
                                                    [numberOfParsedLines:Symfony\Component\Yaml\Parser:private] => 0
                                                    [totalNumberOfLines:Symfony\Component\Yaml\Parser:private] => 
                                                    [lines:Symfony\Component\Yaml\Parser:private] => Array
                                                        (
                                                        )

                                                    [currentLineNb:Symfony\Component\Yaml\Parser:private] => -1
                                                    [currentLine:Symfony\Component\Yaml\Parser:private] => 
                                                    [refs:Symfony\Component\Yaml\Parser:private] => Array
                                                        (
                                                        )

                                                    [skippedLineNumbers:Symfony\Component\Yaml\Parser:private] => Array
                                                        (
                                                        )

                                                    [locallySkippedLineNumbers:Symfony\Component\Yaml\Parser:private] => Array
                                                        (
                                                        )

                                                    [refsBeingParsed:Symfony\Component\Yaml\Parser:private] => Array
                                                        (
                                                        )

                                                )

                                            [defaultContext:Symfony\Component\Serializer\Encoder\YamlEncoder:private] => Array
                                                (
                                                    [yaml_inline] => 0
                                                    [yaml_indent] => 0
                                                    [yaml_flags] => 0
                                                )

                                        )

                                    [3] => Symfony\Component\Serializer\Encoder\CsvEncoder Object
                                        (
                                            [defaultContext:Symfony\Component\Serializer\Encoder\CsvEncoder:private] => Array
                                                (
                                                    [csv_delimiter] => ,
                                                    [csv_enclosure] => "
                                                    [csv_escape_char] => 
                                                    [csv_end_of_line] => 

                                                    [csv_escape_formulas] => 
                                                    [csv_headers] => Array
                                                        (
                                                        )

                                                    [csv_key_separator] => .
                                                    [no_headers] => 
                                                    [as_collection] => 1
                                                    [output_utf8_bom] => 
                                                )

                                        )

                                )

                            [encoderByFormat:Symfony\Component\Serializer\Encoder\ChainEncoder:private] => Array
                                (
                                    [json] => 0
                                )

                        )

                    [decoder:protected] => Symfony\Component\Serializer\Encoder\ChainDecoder Object
                        (
                            [decoders:Symfony\Component\Serializer\Encoder\ChainDecoder:private] => Array
                                (
                                    [0] => Symfony\Component\Serializer\Encoder\JsonEncoder Object
                                        (
                                            [encodingImpl:protected] => Symfony\Component\Serializer\Encoder\JsonEncode Object
                                                (
                                                    [defaultContext:Symfony\Component\Serializer\Encoder\JsonEncode:private] => Array
                                                        (
                                                            [json_encode_options] => 0
                                                        )

                                                )

                                            [decodingImpl:protected] => Symfony\Component\Serializer\Encoder\JsonDecode Object
                                                (
                                                    [serializer:protected] => 
                                                    [defaultContext:Symfony\Component\Serializer\Encoder\JsonDecode:private] => Array
                                                        (
                                                            [json_decode_associative] => 1
                                                            [json_decode_options] => 0
                                                            [json_decode_recursion_depth] => 512
                                                        )

                                                )

                                        )

                                    [1] => Symfony\Component\Serializer\Encoder\XmlEncoder Object
                                        (
                                            [defaultContext:Symfony\Component\Serializer\Encoder\XmlEncoder:private] => Array
                                                (
                                                    [as_collection] => 
                                                    [decoder_ignored_node_types] => Array
                                                        (
                                                            [0] => 7
                                                            [1] => 8
                                                        )

                                                    [encoder_ignored_node_types] => Array
                                                        (
                                                        )

                                                    [load_options] => 2304
                                                    [remove_empty_tags] => 
                                                    [xml_root_node_name] => response
                                                    [xml_type_cast_attributes] => 1
                                                )

                                            [serializer:protected] => Symfony\Component\Serializer\Serializer Object
 *RECURSION*
                                        )

                                    [2] => Symfony\Component\Serializer\Encoder\YamlEncoder Object
                                        (
                                            [dumper:Symfony\Component\Serializer\Encoder\YamlEncoder:private] => Symfony\Component\Yaml\Dumper Object
                                                (
                                                    [indentation:Symfony\Component\Yaml\Dumper:private] => 4
                                                )

                                            [parser:Symfony\Component\Serializer\Encoder\YamlEncoder:private] => Symfony\Component\Yaml\Parser Object
                                                (
                                                    [filename:Symfony\Component\Yaml\Parser:private] => 
                                                    [offset:Symfony\Component\Yaml\Parser:private] => 0
                                                    [numberOfParsedLines:Symfony\Component\Yaml\Parser:private] => 0
                                                    [totalNumberOfLines:Symfony\Component\Yaml\Parser:private] => 
                                                    [lines:Symfony\Component\Yaml\Parser:private] => Array
                                                        (
                                                        )

                                                    [currentLineNb:Symfony\Component\Yaml\Parser:private] => -1
                                                    [currentLine:Symfony\Component\Yaml\Parser:private] => 
                                                    [refs:Symfony\Component\Yaml\Parser:private] => Array
                                                        (
                                                        )

                                                    [skippedLineNumbers:Symfony\Component\Yaml\Parser:private] => Array
                                                        (
                                                        )

                                                    [locallySkippedLineNumbers:Symfony\Component\Yaml\Parser:private] => Array
                                                        (
                                                        )

                                                    [refsBeingParsed:Symfony\Component\Yaml\Parser:private] => Array
                                                        (
                                                        )

                                                )

                                            [defaultContext:Symfony\Component\Serializer\Encoder\YamlEncoder:private] => Array
                                                (
                                                    [yaml_inline] => 0
                                                    [yaml_indent] => 0
                                                    [yaml_flags] => 0
                                                )

                                        )

                                    [3] => Symfony\Component\Serializer\Encoder\CsvEncoder Object
                                        (
                                            [defaultContext:Symfony\Component\Serializer\Encoder\CsvEncoder:private] => Array
                                                (
                                                    [csv_delimiter] => ,
                                                    [csv_enclosure] => "
                                                    [csv_escape_char] => 
                                                    [csv_end_of_line] => 

                                                    [csv_escape_formulas] => 
                                                    [csv_headers] => Array
                                                        (
                                                        )

                                                    [csv_key_separator] => .
                                                    [no_headers] => 
                                                    [as_collection] => 1
                                                    [output_utf8_bom] => 
                                                )

                                        )

                                )

                            [decoderByFormat:Symfony\Component\Serializer\Encoder\ChainDecoder:private] => Array
                                (
                                    [json] => 0
                                )

                        )

                    [normalizers:Symfony\Component\Serializer\Serializer:private] => Array
                        (
                            [0] => Symfony\Component\Serializer\Normalizer\DateTimeNormalizer Object
                                (
                                    [defaultContext:Symfony\Component\Serializer\Normalizer\DateTimeNormalizer:private] => Array
                                        (
                                            [datetime_format] => Y-m-d\TH:i:sP
                                            [datetime_timezone] => 
                                        )

                                )

                            [1] => Symfony\Component\Serializer\Normalizer\ObjectNormalizer Object
                                (
                                    [defaultContext:protected] => Array
                                        (
                                            [allow_extra_attributes] => 1
                                            [circular_reference_handler] => 
                                            [circular_reference_limit] => 1
                                            [ignored_attributes] => Array
                                                (
                                                )

                                            [exclude_from_cache_key] => Array
                                                (
                                                    [0] => circular_reference_limit_counters
                                                )

                                        )

                                    [classMetadataFactory:protected] => 
                                    [nameConverter:protected] => Gebler\Doclite\DocLiteNameConverter Object
                                        (
                                            [customId:Gebler\Doclite\DocLiteNameConverter:private] => 
                                        )

                                    [serializer:protected] => Symfony\Component\Serializer\Serializer Object
 *RECURSION*
                                    [propertyTypeExtractor:Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer:private] => Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor Object
                                        (
                                            [mutatorPrefixes:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array
                                                (
                                                    [0] => add
                                                    [1] => remove
                                                    [2] => set
                                                )

                                            [accessorPrefixes:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array
                                                (
                                                    [0] => get
                                                    [1] => is
                                                    [2] => has
                                                    [3] => can
                                                )

                                            [arrayMutatorPrefixes:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array
                                                (
                                                    [0] => add
                                                    [1] => remove
                                                )

                                            [enableConstructorExtraction:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 1
                                            [methodReflectionFlags:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 1
                                            [magicMethodsFlags:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 3
                                            [propertyReflectionFlags:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 1
                                            [inflector:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Symfony\Component\String\Inflector\EnglishInflector Object
                                                (
                                                )

                                            [arrayMutatorPrefixesFirst:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array
                                                (
                                                    [0] => add
                                                    [1] => remove
                                                    [2] => set
                                                )

                                            [arrayMutatorPrefixesLast:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array
                                                (
                                                    [0] => set
                                                    [1] => remove
                                                    [2] => add
                                                )

                                        )

                                    [typesCache:Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer:private] => Array
                                        (
                                        )

                                    [attributesCache:Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer:private] => Array
                                        (
                                        )

                                    [objectClassResolver:Symfony\Component\Serializer\Normalizer\AbstractObjectNormalizer:private] => 
                                    [classDiscriminatorResolver:protected] => 
                                    [propertyAccessor:protected] => Symfony\Component\PropertyAccess\PropertyAccessor Object
                                        (
                                            [magicMethodsFlags:Symfony\Component\PropertyAccess\PropertyAccessor:private] => 3
                                            [ignoreInvalidIndices:Symfony\Component\PropertyAccess\PropertyAccessor:private] => 1
                                            [ignoreInvalidProperty:Symfony\Component\PropertyAccess\PropertyAccessor:private] => 
                                            [cacheItemPool:Symfony\Component\PropertyAccess\PropertyAccessor:private] => 
                                            [propertyPathCache:Symfony\Component\PropertyAccess\PropertyAccessor:private] => Array
                                                (
                                                )

                                            [readInfoExtractor:Symfony\Component\PropertyAccess\PropertyAccessor:private] => Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor Object
                                                (
                                                    [mutatorPrefixes:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array
                                                        (
                                                        )

                                                    [accessorPrefixes:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array
                                                        (
                                                            [0] => get
                                                            [1] => is
                                                            [2] => has
                                                            [3] => can
                                                        )

                                                    [arrayMutatorPrefixes:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array
                                                        (
                                                            [0] => add
                                                            [1] => remove
                                                        )

                                                    [enableConstructorExtraction:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 
                                                    [methodReflectionFlags:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 1
                                                    [magicMethodsFlags:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 3
                                                    [propertyReflectionFlags:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 1
                                                    [inflector:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Symfony\Component\String\Inflector\EnglishInflector Object
                                                        (
                                                        )

                                                    [arrayMutatorPrefixesFirst:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array
                                                        (
                                                            [0] => add
                                                            [1] => remove
                                                        )

                                                    [arrayMutatorPrefixesLast:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array
                                                        (
                                                            [0] => remove
                                                            [1] => add
                                                        )

                                                )

                                            [writeInfoExtractor:Symfony\Component\PropertyAccess\PropertyAccessor:private] => Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor Object
                                                (
                                                    [mutatorPrefixes:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array
                                                        (
                                                            [0] => set
                                                        )

                                                    [accessorPrefixes:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array
                                                        (
                                                            [0] => get
                                                            [1] => is
                                                            [2] => has
                                                            [3] => can
                                                        )

                                                    [arrayMutatorPrefixes:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array
                                                        (
                                                            [0] => add
                                                            [1] => remove
                                                        )

                                                    [enableConstructorExtraction:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 
                                                    [methodReflectionFlags:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 1
                                                    [magicMethodsFlags:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 3
                                                    [propertyReflectionFlags:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => 1
                                                    [inflector:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Symfony\Component\String\Inflector\EnglishInflector Object
                                                        (
                                                        )

                                                    [arrayMutatorPrefixesFirst:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array
                                                        (
                                                            [0] => add
                                                            [1] => remove
                                                            [2] => set
                                                        )

                                                    [arrayMutatorPrefixesLast:Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor:private] => Array
                                                        (
                                                            [0] => set
                                                            [1] => remove
                                                            [2] => add
                                                        )

                                                )

                                            [readPropertyCache:Symfony\Component\PropertyAccess\PropertyAccessor:private] => Array
                                                (
                                                )

                                            [writePropertyCache:Symfony\Component\PropertyAccess\PropertyAccessor:private] => Array
                                                (
                                                )

                                        )

                                    [discriminatorCache:Symfony\Component\Serializer\Normalizer\ObjectNormalizer:private] => Array
                                        (
                                        )

                                    [objectClassResolver:Symfony\Component\Serializer\Normalizer\ObjectNormalizer:private] => Closure Object
                                        (
                                            [this] => Symfony\Component\Serializer\Normalizer\ObjectNormalizer Object
 *RECURSION*
                                            [parameter] => Array
                                                (
                                                    [$class] => 
                                                )

                                        )

                                )

                            [2] => Symfony\Component\Serializer\Normalizer\ArrayDenormalizer Object
                                (
                                    [denormalizer:protected] => Symfony\Component\Serializer\Serializer Object
 *RECURSION*
                                )

                        )

                    [denormalizerCache:Symfony\Component\Serializer\Serializer:private] => Array
                        (
                        )

                    [normalizerCache:Symfony\Component\Serializer\Serializer:private] => Array
                        (
                        )

                )

            [nameConverter:Gebler\Doclite\Collection:private] => Gebler\Doclite\DocLiteNameConverter Object
                (
                    [customId:Gebler\Doclite\DocLiteNameConverter:private] => 
                )

            [ftsIndexes:Gebler\Doclite\Collection:private] => Array
                (
                )

        )

    [jsonSchema:Gebler\Doclite\Document:private] => 
)
------------------------------------------------------------------

**Comment by dwgebler** [comment]
@REDAL the document object has a `toArray()` method if you want a simple array of all the document fields, e.g. 

```
$collection = $db->collection('test');
$document = $collection->get();

$id = $document->getId();
$document->setFirstName('John');
$firstName = $document->getFirstName();
$document->setLastName('Smith');
$document->save();

var_dump($document->toArray());
```

**Comment by REDAL** [comment]
thanks a lot, David, really I am very grateful,

I did searched the official GitHub page, for that toArray(), didn't found it,

can you please, refer me to the complete documentation page 

kindest regards

**Comment by dwgebler** [comment]
The complete documentation is the README, in addition the code itself is documented such as to allow your IDE to auto-complete and show inline documentation for functions etc. `toArray()` is not documented in the README as it is not a particularly common use-case.

**Comment by REDAL** [comment]
again David, thank you for all the great work you offered to us 
love and respect

**Comment by REDAL** [comment]
@dwgebler 
for the ID of the document, as I saw, it's not a numeric,
how can we retrieve for examples documents where id between 1 and 100

**Comment by dwgebler** [comment]
You don't have to use the auto-generated ID - it is only created for you if you don't specify an ID when you create a document. You can either set your own ID at the point of creating a document, or add another field to the document to use alongside the auto-generated ID.

https://github.com/dwgebler/doclite#document-unique-id

**Comment by REDAL** [comment]
great,
thanks a lot David
