### ISSUE TITLE
How do you update document?

### ISSUE THREAD

**Issue by mitmelon** [dwgebler/doclite#19]
There are no examples to show how to update a document.

**Comment by mitmelon** [comment]
I think i got it... Incase anybody that might need this later

```
/* 
Update document function
@params
String $collection : Your collection name
String $id : Your document id to update
Array $data : The data to update
*/
function update($collection, $id, array $data){
    $db = $userCollection->collection($collection);
    $user = $db->get($id);
    if (is_array($data) and count($data) > 0) {
        foreach ($data as $key => $value) {
            $user->$key($value);
         }
    }
   $user->save();
}
```

I will appreciate if this could also be added to the current readme documentations to help others like me.

**Comment by dwgebler** [comment]
Hello, setting document values and saving documents is covered in detail in this section of the documentation:

https://github.com/dwgebler/doclite#documents

As well a quick example in the usage overview:

https://github.com/dwgebler/doclite#getting-started

Assuming you are using the built-in DocLite `Document` class and not a custom class, you can either call the magic `set` functions in the form of `$document->setPropertyName($value)` e.g. `$document->setFirstName('John')` or you can set as public properties e.g. `$document->first_name = 'John'`. You can then call `$document->save()` to update the document in storage.
