### ISSUE TITLE
extensive documentation for doclite

### ISSUE THREAD

**Issue by REDAL** [dwgebler/doclite#24]
Hi @dwgebler 

I find it difficult to manipulate it easily in some scenarios, otherwise it's super cool,

also, if you do have extensive documentation of the library, it will be better to read it and study it further and reduce the questions posted.

kindest regards

**Comment by REDAL** [comment]
how to do for example
orderBy for findAll

**Comment by dwgebler** [comment]
@REDAL the `findAll()` method simply returns all documents in a collection (in no specific order). To fetch all documents in a collection, you just need to use the query builder interface instead:

```php
$db = new FileDatabase('./data.db');
$test = $db->collection('user');
$data = $test->orderBy('username', 'ASC')->fetch(); // or fetchArray() if you don't want a generator
```
