### ISSUE TITLE
critical issue when inserting crash

### ISSUE THREAD

**Issue by REDAL** [dwgebler/doclite#25]
Hi @dwgebler  

there is a serious issue when for example trying to generate a long list of arrays, and the server goes down for any reason, the database became unusable !! and can't retrieve data, this is what I get, when trying to get a full list of records,

Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 5 database is locked in \vendor\dwgebler\doclite\src\Connection\DatabaseConnection.php:281 Stack trace: #0 \vendor\dwgebler\doclite\src\Connection\DatabaseConnection.php(281): PDO->exec('DELETE FROM "us...') #1 \vendor\dwgebler\doclite\src\Database.php(935): Gebler\Doclite\Connection\DatabaseConnection->exec('DELETE FROM "us...') #2 \vendor\dwgebler\doclite\src\Collection.php(402): Gebler\Doclite\Database->getCache('users_cache', 'dqlQuery', '085a8b0e3654018...', Object(DateTimeImmutable)) #3 [internal function]: Gebler\Doclite\Collection->getCache('dqlQuery', Array) #4 \vendor\dwgebler\doclite\src\Collection.php(340): Generator->current() #5 [internal function]: Gebler\Doclite\Collection->executeDqlQuery('SELECT COUNT (D...', Array, true) #6 \vendor\dwgebler\doclite\src\QueryBuilder.php(248): Generator->current() #7 \vendor\dwgebler\doclite\src\Collection.php(967): Gebler\Doclite\QueryBuilder->count() #8 bench.php(119): Gebler\Doclite\Collection->count() #9 bench.php(30): generateUsers() #10 {main} Next Gebler\Doclite\Exception\DatabaseException: Error executing statement in \vendor\dwgebler\doclite\src\Connection\DatabaseConnection.php on line 290

any thoughts, and how can avoid this issue in the future, I am benchmarking the library to decide which I will use it an important project for me, and don't want to get stuck in the future and can't resolve it.

and thank you again for the awesome library, I am a pro nosql databases to a high level
regards

**Comment by dwgebler** [comment]
This is not a DocLite error, it's an SQLite error. SQLite databases can occasionally become stuck in a locked state if e.g. there is a system crash while a running process has a write lock. If it's still locked after restarting the OS, you can usually resolve by copying the DB file to a new file, then copying the new file back to the original file name. Otherwise you can use the sqlite command line client to make a dump of the locked database and reimport it in to a new database file.

**Comment by dwgebler** [comment]
Btw @REDAL in case you're not familiar with how this works, the file lock is something maintained by your operating system, not DocLite or within the database file itself. Basically you either have another process open which is accessing the same database file at the same time for an exclusive lock (i.e. write operation), or your operating system itself is wrongly holding a lock it should have released. Steps for investigating and fixing this depend on what your particular operating system is. First thing you want to check is whether any other running process has a lock on the db file.

**Comment by dwgebler** [comment]
See https://www.sqlite.org/lockingv3.htm for reference

**Comment by REDAL** [comment]
hi again,

the link above not working,

also I do no it's a ock mechanism, but like I demonstrated above, it happened when the writing process crash for any reason, the whole database will be inaccessible, and as you know this is a serious problem.

btw, you can resolve the issue not only by copying the database which is not a reliable solution, especially in a prouction environment!, you can also do that by optimizing the database.

I've asked for any thing built in in doclite for example is there in doclite

Enable memory mapping, Increase the page size, can we handle this like in sqlite native engine ?

regards

**Comment by dwgebler** [comment]
Link corrected. There aren't functions in DocLite for memory mapping and page size but I believe these can be set via PRAGMA statements so it would be easy to do a pull request to add these commands. See for example https://github.com/dwgebler/doclite/blob/main/src/Database.php#L542

Contributions are always welcome.

**Comment by REDAL** [comment]
good I'll add those pragma, it really helps,
btw, why don't work together to offer it like a hosted database with API's to manage
what do you think
