### ISSUE TITLE
doclite returns nothing if searched data cnotain /

### ISSUE THREAD

**Issue by REDAL** [dwgebler/doclite#26]
Hi @dwgebler 

when trying to fetch data with "/" it returns nothing, I've tried to escape it, but nothing retruned

[email] => eJxLzs8rSUwucUjOz0ut0EupAgA2mAZW                           this works when querying with
[website] => eJwrLy/XS87PS63QS6kCAB9bBL0=                                 this returns nothing when querying with that data

any help

**Comment by dwgebler** [comment]
Hello,
Are you able to provide a

**Comment by REDAL** [comment]
Hi again,

plain simple,

$merchantArr = $merchantCollection->findOneBy([
            "website" => "eJwrLy/XS87PS63QS6kCAB9bBL0=",
            "_sts" => 1,
        ]);

I did get around it, by replacing / by another character, before storing it, and when quering it again, replace the / with same char, just wanted to know, if this can be fixed by the library 

regards

**Comment by dwgebler** [comment]
Hello,
I will need to see a _complete_ code sample which reproduces the issue you're describing. For example, the following code works as expected and returns the previously inserted document:

```
$test = $db->collection('foobar');
$doc = $test->get();
$doc->baz = 'bar/with/slash';
$doc->save();

$result = $test->findOneBy(['baz' => 'bar/with/slash']);
```

So there isn't any known issue in general with querying document fields where the data contains a slash.

**Comment by REDAL** [comment]
Hi again,

I used base64encode, to encode data, and used it to encode user input data so I can query it again, when the generated data contains / it doesnt work,

this is the scenario

**Comment by dwgebler** [comment]
Okay so I see the bug. It arises because DocLite uses the Symfony serializer to convert objects to JSON for storage, which by default uses `json_encode` but doesn't give us an interface to avoid escaping forward slashes (which are normally escaped in JSON). So when we try to find in DocLite, we get a query which is tries to compare two sets of values like in the following query I've written to demonstrate:

```
SELECT json_extract(json, "$.website","$._sts") AS actual, json_array("eJwrLy/XS87PS63QS6kCAB9bBL0=",1) AS params FROM "foobar";
```

And the result would be something like:

```
actual	params
["eJwrLy\/XS87PS63QS6kCAB9bBL0=",1]	["eJwrLy/XS87PS63QS6kCAB9bBL0=",1]
```

As you can see, what's pulled out of the DB to compare in the generated WHERE clause has an escaped slash, whereas the parameters we're trying to compare don't. But you can't just stick in an escape on the slash (`eJwrLy\/XS87PS63QS6kCAB9bBL0=`) because when that gets passed in to SQLite, it will end up being double-escaped to `\\/` and won't match.

I think I can fix this on two fronts: one by stripping escaped forward slashes from the result of Symfony's serializer call when a document is saved, the other by creating a custom SQLite function in DocLite to unquote the result of `json_extract`.

**Comment by dwgebler** [comment]
@REDAL try installing latest version 1.1.7 and hopefully this fixes your problem.

**Comment by dwgebler** [comment]
@REDAL as an alternative, if you don't wish to or can't readily upgrade to the latest release, you can find your documents via the query builder instead. This doesn't have the same issue as each field is extracted individually in the resultant SQL query.

```
$collection->where('website', '=', 'value/with/slash')->and('_sts', '=', 1)->fetchArray();
```

**Comment by REDAL** [comment]
@dwgebler  thank you for the engagement, I highly appreciate it.
like I said I did get around it using replace / by another char, and it worked for me,
I wanted to notify just to find an in built solution, and thats what you did :)

also, if you can give us a more detailled documentation, it will be great, because I find it difficult, there is many things missing, especially in the functions syntaxe and so

kindest regards

**Comment by REDAL** [comment]
by the way I did upgraded, and disabled the replacing functionality and it works without it :)

I also implemented a searchable encrypted functionnality :)

just if you can do a deeper documentation, I've migrated to doclite from sleekdb, because of its peformance since its sqlite based, but I find the first has detailled documentaiton than doclite, and may be for new commers like me will find it intimidating or difficult to switch because of that.

I am pretty sure that the community really appreciate your effort and so Iam I , am greatly appreciating it

**Comment by dwgebler** [comment]
One way to improve the documentation is to contribute and raise a pull
request :)

**Comment by REDAL** [comment]
I would like to contribute, but like I said, I am new to doclite, how can I do that if I can't figure out how to use it

**Comment by dwgebler** [comment]
There's not an IN operator in the current release. Looks like you want to find any documents where the `name` field is either "a" or "b", right? You can do this, it's just more verbose:

```
// $document->name = 'John'
$collection->where('name', '=', 'Bob')->or('name', '=', 'John')->fetch();
```

**Comment by REDAL** [comment]
> There's not an IN operator in the current release. Looks like you want to find any documents where the `name` field is either "a" or "b", right? You can do this, it's just more verbose:
> 
> ```
> // $document->name = 'John'
> $collection->where('name', '=', 'Bob')->or('name', '=', 'John')->fetch();
> ```

ITS NOT DEASABLE ESPECIALLY IF THE ARRAY IS LONG OR USER INPUT BASED ARRAY, WHERE I CAN'T KNOW HOW LONG WILL BE

**Comment by REDAL** [comment]
tried multiple solutions but no one worked

$search_terms = ['Bob', 'John'];

$results = $merchantCollection->where('name[]', '=', $search_terms[0]);
    for ($i = 1; $i < count($search_terms); $i++) {
        $results->or('name[]', '=', $search_terms[$i]);
    }
    $results = $results->fetch();

**Comment by dwgebler** [comment]
If name is a single value, there is no need for square brackets on it.

where ('name[]'...) is for searching a document where name is a list (i.e.
an array of strings in your document object).

**Comment by REDAL** [comment]
tried multiple solutions and one worked for me,
I used closures

thank you for your help @dwgebler

**Comment by REDAL** [comment]
I also added $db->setPragma("vacuum"); // vacuum  -  optimize
