### ISSUE TITLE
column data issue with nested rows or JOIN

### ISSUE THREAD

**Issue by REDAL** [dwgebler/doclite#29]
Hi @dwgebler 

I have a weird issue, 

I save encrypted data, in 2 tables, related by ID

when fetching the rows individually, without JOIN, and decrypting data, it works

when, JOIN the two tables, and decrypt the main row, it decrypt well,
but when, decrypting the joined rows, it does not !!!

when I copy past the row field data, and decrypt it, it decrypt, but when decrypt it in loop it does not

// this works

    $appArr = $appsCollection->findOneBy([
        "_sts" => 1,
    ]);
    
    $app = $appArr->toArray();
    
    $app["api_id"]                        = decryptData($app["api_id"]);

    echo "<pre>";
    print_r($app);
    echo "</pre>";

// this works partially !!!

foreach($merchantCollection->where('__id', '!=', "")->join($appsCollection, "merchant_hid","_hid")->fetch() as $merchantArr) {
        $merchant2 = $merchantArr->toArray();
    
        $merchant2["merchant_user2"]                 = decryptData($merchant2["merchant_user2"]); // this works well

        foreach ($merchant2["apps"] as $key => $value) {

            $merchant2["apps"][$key]["api_id"]                        = decryptData($value["api_id"]); // this does not work

        }
        
        echo "<pre>";
        print_r($merchant2);
        echo "</pre>";
    }

**Comment by REDAL** [comment]
its like when joining it, the data is altered and changed, thats why the decryption algorithm return an empty data !

**Comment by REDAL** [comment]
I will @dwgebler send you the script via your email,

honestly, I fall in love with NoSQL libraries, especially doclite, but since it lacks a lot of documentation, and cost me a lot of time like days, just to figure out simple things, the documentation is very very poor, while doclite has more potential than for example SleekDB, but SleekDB has better-detailed documentation, its almost impossible to not find anything related to it in the documentation. but since it is not as powerful as sqlite, which doclite is based on,  I decided to move on to MySQL (actually goback to mysql). I will gladly come back to doclite if it bring better fully detailled documentation. it is sad to see such a nice library like yours, with just a little of stars and not mass adopted while the concept is good (nosql database managed by library all in one), which I can assure you, it's because they couldn't find solutions in time and easily, that's what libraries are made for, to make it easy in certain things, not inverse.

finally, I really hope all the best for you and for doclite, see u soon bro

**Comment by dwgebler** [comment]
> cost me a lot of time like days, just to figure out simple things, the documentation is very very poor

I've provided what I feel is reasonably comprehensive documentation for the library; what do you feel is missing or undocumented which could be improved in the README?

**Comment by dwgebler** [comment]
Closing the issue as I have insufficient information to reproduce or investigate.

**Comment by REDAL** [comment]
thank you for your help

REDA ALOUI
CEO Conex

Mobile     : 0561716060
Addresse : RC, bureau n°01, Centre d'affaires kheir eddine, la gare -Biskra
Siteweb   : www.c<http://www.anrsoft.net/>onex.dz / www.elkashaf.com<http://www.anr-soft.com/>
________________________________
De : dwgebler ***@***.***>
Envoyé : samedi 1 avril 2023 02:49
À : dwgebler/doclite ***@***.***>
Cc : redaloui ***@***.***>; Author ***@***.***>
Objet : Re: [dwgebler/doclite] column data issue with nested rows or JOIN (Issue #29)


Closing the issue as I have insufficient information to reproduce or investigate.
