### ISSUE TITLE
how to do condition on join table

### ISSUE THREAD

**Issue by REDAL** [dwgebler/doclite#30]
@dwgebler  Hi

how to do condition query on joined table

foreach($merchantCollection->where('__id', '!=', "")->join($appsCollection, "merchant_hid","_hid")->and('_id', '=', 2)->fetch() as $merchantArr) {

I want to apply this ->and('_id', '=', 2) on the second table $appsCollection

didn't work for me

**Comment by dwgebler** [comment]
There's not a way to do that at the moment; conditions can only be applied to the left side of the join ($merchantCollection in your example). You'd need to get all matching results from the conditional query on $merchantCollection joined with $appsCollection then filter the `apps` entries in your application code.
