### ISSUE TITLE
Benchmark: DocLite

### ISSUE THREAD

**Issue by Awilum** [dwgebler/doclite#4]
Please provide any benchmarks for DocLite.
Thanks!

**Comment by dwgebler** [comment]
Hi @Awilum I have tested DocLite with documents up to 1MB, and collections of up to a million documents at a total database size of around 2GB, without significantly pushing performance. The limits of DocLite are largely the limits of SQLite. This means many factors can impact any benchmarks, including the underlying file system, the sync mode, the journal mode, use of indexes, database optimization and others. As such, your mileage with DocLite may vary. If you would like to perform any benchmarking using specific tools or tests and document the results, I'd be happy to include them - but I don't make any warranties myself.

> Broadly speaking, DocLite is suitable for the same uses cases as the underlying SQLite engine it is built on, but where you desire a NoSQL solution.
